before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RVTf95own3Ve1ECYHfzii460ulwAWxzru1DddjhvZ58TIrXwQOrBrR5fZquBkhE8B8F7EgwSSM7Vg7kW4zubhTab9wWVUGFPWzZRzm5lqQ6GTucarRbvClpW3CLxDp/A6L4EaR5hEZrN717bX2uoeszBhlj5Dl2swn6LstAuDcNatjUjToGjZsnQPzxqoH61vQnW7Kl6HjD3T0tJPcblmqBeo4m7lv0Bps+Tlkf4iVAE4mQD3hVmzW7cOR+Ll/wKj1TIEP3fOjv4NGP7Bn0T/amoYkSCBgvcgd3RfHZjN/iFozjG+F1i+AuaDSnxt/MBtbjHS9geNmoGQPy8LnMjYQrGpSzsiI9SaOikNhxTkk65fGOW5ZjTPM3Q+5qOn9ICLoz5I0MNbRSCTZNW73+buQAUN2g/EYl6+NnG1lBby7+gYc5qrVAY6eIE/JdQ/RnQ3CPnrmOsFMfPSstGS35zztHlrOY2GNcE6FBv+K91WBjn/wUYmbly9V/vCemrJ2ZYrKj7Qv3j5VBlkLXvJdjz5rXFGvGJMS0VkIFmcznRU1gqjblhg+fybbVqcEY4zWaR8o/wL5Mp7YlMAwci0LS7u+q5LlfumptviqHH+NF1Aea280mJc1S3pjUScSFTPi/tHwTQohKVipV4WCaGCosryQ0K/9QhM0FHmqz051d5jDk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
